#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Linqjueves
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="LinqJueves")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertPacientes(Pacientes instance);
    partial void UpdatePacientes(Pacientes instance);
    partial void DeletePacientes(Pacientes instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Linqjueves.Properties.Settings.Default.LinqJuevesConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Pacientes> Pacientes
		{
			get
			{
				return this.GetTable<Pacientes>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_Alta")]
		public int SP_Alta([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Inscripcion", DbType="NVarChar(10)")] string inscripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="NVarChar(15)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Apellidos", DbType="NVarChar(50)")] string apellidos, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(12)")] string sexo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fecha", DbType="NVarChar(50)")] string fecha, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Direccion", DbType="NVarChar(50)")] string direccion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumSS", DbType="NVarChar(10)")] string numSS)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), inscripcion, nombre, apellidos, sexo, fecha, direccion, numSS);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_Baja")]
		public int SP_Baja([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Inscripcion", DbType="NVarChar(10)")] string inscripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), inscripcion);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ListarAltas")]
		public ISingleResult<SP_ListarAltasResult> SP_ListarAltas()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_ListarAltasResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ModificarAlta")]
		public int SP_ModificarAlta([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Inscripcion", DbType="NVarChar(10)")] string inscripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="NVarChar(15)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Apellidos", DbType="NVarChar(50)")] string apellidos, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(12)")] string sexo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fecha", DbType="NVarChar(50)")] string fecha, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Direccion", DbType="NVarChar(50)")] string direccion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumSS", DbType="NVarChar(10)")] string numSS)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), inscripcion, nombre, apellidos, sexo, fecha, direccion, numSS);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_AltaDoctor")]
		public int SP_AltaDoctor([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Hospital_Cod", DbType="NVarChar(5)")] string hospital_Cod, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Num_Doctor", DbType="NVarChar(5)")] string num_Doctor, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Apellido", DbType="NVarChar(15)")] string apellido, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Especialidad", DbType="NVarChar(20)")] string especialidad)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), hospital_Cod, num_Doctor, apellido, especialidad);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_BajaDoctor")]
		public int SP_BajaDoctor([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Hospital_Cod", DbType="NVarChar(5)")] string hospital_Cod)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), hospital_Cod);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ListarDoctor")]
		public ISingleResult<SP_ListarDoctorResult> SP_ListarDoctor()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_ListarDoctorResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ModificarDoctor")]
		public int SP_ModificarDoctor([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Hospital_Cod", DbType="NVarChar(5)")] string hospital_Cod, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Num_Doctor", DbType="NVarChar(5)")] string num_Doctor, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Apellido", DbType="NVarChar(15)")] string apellido, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Especialidad", DbType="NVarChar(20)")] string especialidad)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), hospital_Cod, num_Doctor, apellido, especialidad);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Pacientes")]
	public partial class Pacientes : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Inscripción;
		
		private string _Nombre;
		
		private string _Apellidos;
		
		private string _sexo;
		
		private string _Fecha;
		
		private string _Direccion;
		
		private string _NumSS;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnInscripciónChanging(string value);
    partial void OnInscripciónChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnApellidosChanging(string value);
    partial void OnApellidosChanged();
    partial void OnsexoChanging(string value);
    partial void OnsexoChanged();
    partial void OnFechaChanging(string value);
    partial void OnFechaChanged();
    partial void OnDireccionChanging(string value);
    partial void OnDireccionChanged();
    partial void OnNumSSChanging(string value);
    partial void OnNumSSChanged();
    #endregion
		
		public Pacientes()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Inscripción", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Inscripción
		{
			get
			{
				return this._Inscripción;
			}
			set
			{
				if ((this._Inscripción != value))
				{
					this.OnInscripciónChanging(value);
					this.SendPropertyChanging();
					this._Inscripción = value;
					this.SendPropertyChanged("Inscripción");
					this.OnInscripciónChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(15)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellidos", DbType="NVarChar(50)")]
		public string Apellidos
		{
			get
			{
				return this._Apellidos;
			}
			set
			{
				if ((this._Apellidos != value))
				{
					this.OnApellidosChanging(value);
					this.SendPropertyChanging();
					this._Apellidos = value;
					this.SendPropertyChanged("Apellidos");
					this.OnApellidosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sexo", DbType="NVarChar(12) NOT NULL", CanBeNull=false)]
		public string sexo
		{
			get
			{
				return this._sexo;
			}
			set
			{
				if ((this._sexo != value))
				{
					this.OnsexoChanging(value);
					this.SendPropertyChanging();
					this._sexo = value;
					this.SendPropertyChanged("sexo");
					this.OnsexoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="NVarChar(50)")]
		public string Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="NVarChar(50)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this.OnDireccionChanging(value);
					this.SendPropertyChanging();
					this._Direccion = value;
					this.SendPropertyChanged("Direccion");
					this.OnDireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumSS", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string NumSS
		{
			get
			{
				return this._NumSS;
			}
			set
			{
				if ((this._NumSS != value))
				{
					this.OnNumSSChanging(value);
					this.SendPropertyChanging();
					this._NumSS = value;
					this.SendPropertyChanged("NumSS");
					this.OnNumSSChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class SP_ListarAltasResult
	{
		
		private string _Inscripción;
		
		private string _Nombre;
		
		private string _Apellidos;
		
		private string _sexo;
		
		private string _Fecha;
		
		private string _Direccion;
		
		private string _NumSS;
		
		public SP_ListarAltasResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Inscripción", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Inscripción
		{
			get
			{
				return this._Inscripción;
			}
			set
			{
				if ((this._Inscripción != value))
				{
					this._Inscripción = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(15)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellidos", DbType="NVarChar(50)")]
		public string Apellidos
		{
			get
			{
				return this._Apellidos;
			}
			set
			{
				if ((this._Apellidos != value))
				{
					this._Apellidos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sexo", DbType="NVarChar(12) NOT NULL", CanBeNull=false)]
		public string sexo
		{
			get
			{
				return this._sexo;
			}
			set
			{
				if ((this._sexo != value))
				{
					this._sexo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="NVarChar(50)")]
		public string Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this._Fecha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="NVarChar(50)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this._Direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumSS", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string NumSS
		{
			get
			{
				return this._NumSS;
			}
			set
			{
				if ((this._NumSS != value))
				{
					this._NumSS = value;
				}
			}
		}
	}
	
	public partial class SP_ListarDoctorResult
	{
		
		private string _Hospital_Cod;
		
		private string _Número_Doctor;
		
		private string _Apellido;
		
		private string _Especialidad;
		
		public SP_ListarDoctorResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hospital_Cod", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
		public string Hospital_Cod
		{
			get
			{
				return this._Hospital_Cod;
			}
			set
			{
				if ((this._Hospital_Cod != value))
				{
					this._Hospital_Cod = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Número_Doctor", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
		public string Número_Doctor
		{
			get
			{
				return this._Número_Doctor;
			}
			set
			{
				if ((this._Número_Doctor != value))
				{
					this._Número_Doctor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="NVarChar(15)")]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this._Apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Especialidad", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Especialidad
		{
			get
			{
				return this._Especialidad;
			}
			set
			{
				if ((this._Especialidad != value))
				{
					this._Especialidad = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
