//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPMacroEjercicioJueves
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedido
    {
        public int id { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public Nullable<int> id_comercial { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual comercial comercial { get; set; }
    }
}
