<?xml version="1.0" encoding="utf-8"?><Database Name="SimulacroExamenModulo2" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=CADAVILES04\SQLEXPRESS;Initial Catalog=SimulacroExamenModulo2;Integrated Security=True" SettingsObjectName="SimulacroExamenModulo2.Properties.Settings" SettingsPropertyName="SimulacroExamenModulo2ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Empleados" Member="Empleados">
    <Type Name="Empleados">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Apellido" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Edad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Casado" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.SP_Alta" Method="SP_Alta">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Apellido" Parameter="apellido" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="Edad" Parameter="edad" Type="System.Int32" DbType="Int" />
    <Parameter Name="Casado" Parameter="casado" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_ListarAltas" Method="SP_ListarAltas">
    <ElementType Name="SP_ListarAltasResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Apellido" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Edad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Casado" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_ModificarAlta" Method="SP_ModificarAlta">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Apellido" Parameter="apellido" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Edad" Parameter="edad" Type="System.Int32" DbType="Int" />
    <Parameter Name="Casado" Parameter="casado" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_BuscarEmpleado" Method="SP_BuscarEmpleado">
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="NVarChar(20)" />
    <ElementType Name="SP_BuscarEmpleadoResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Apellido" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Edad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Casado" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_Baja" Method="SP_Baja">
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
</Database>